; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:attiny2313]
platform = atmelavr
board = attiny2313
monitor_speed = 9600
monitor_port = COM43
upload_protocol = stk500v2
upload_port = COM10
board_fuses.efuse = 0xFF 
board_fuses.hfuse = 0xDF
board_fuses.lfuse = 0xEF

